(function(a,z){function e(a){w[w.length]=a}function q(a){u.className=u.className.replace(new RegExp(" \\b"+a+"\\b"),"")}function n(a,e){for(var c=0,h=a.length;c<h;c++)e.call(a,a[c],c)}function v(){u.className=u.className.replace(/ (w-|eq-|gt-|gte-|lt-|lte-|portrait|no-portrait|landscape|no-landscape)\d+/g,"");var b=a.innerWidth||u.clientWidth,f=a.outerWidth||a.screen.width;l.screen.innerWidth=b;l.screen.outerWidth=f;e("w-"+b);n(c.screens,function(a){b>a?(c.screensCss.gt&&e("gt-"+a),c.screensCss.gte&&
e("gte-"+a)):b<a?(c.screensCss.lt&&e("lt-"+a),c.screensCss.lte&&e("lte-"+a)):b===a&&(c.screensCss.lte&&e("lte-"+a),c.screensCss.eq&&e("e-q"+a),c.screensCss.gte&&e("gte-"+a))});var f=a.innerHeight||u.clientHeight,k=a.outerHeight||a.screen.height;l.screen.innerHeight=f;l.screen.outerHeight=k;l.feature("portrait",f>b);l.feature("landscape",f<b)}function t(){a.clearTimeout(C);C=a.setTimeout(v,100)}var r=a.document,k=a.navigator,x=a.location,u=r.documentElement,w=[],c={screens:[240,320,480,640,768,800,
1024,1280,1440,1680,1920],screensCss:{gt:!0,gte:!1,lt:!0,lte:!1,eq:!1},browsers:[{ie:{min:6,max:10}}],browserCss:{gt:!0,gte:!1,lt:!0,lte:!1,eq:!0},section:"-section",page:"-page",head:"head"};if(a.head_conf)for(var b in a.head_conf)a.head_conf[b]!==z&&(c[b]=a.head_conf[b]);var l=a[c.head]=function(){l.ready.apply(null,arguments)};l.feature=function(a,c,b){if(!a)return u.className+=" "+w.join(" "),w=[],l;"[object Function]"===Object.prototype.toString.call(c)&&(c=c.call());e((c?"":"no-")+a);l[a]=!!c;
b||(q("no-"+a),q(a),l.feature());return l};l.feature("js",!0);b=k.userAgent.toLowerCase();k=/mobile|android|kindle|silk|midp|(windows nt 6\.2.+arm|touch)/.test(b);l.feature("mobile",k,!0);l.feature("desktop",!k,!0);b=/(chrome|firefox)[ \/]([\w.]+)/.exec(b)||/(iphone|ipad|ipod)(?:.*version)?[ \/]([\w.]+)/.exec(b)||/(android)(?:.*version)?[ \/]([\w.]+)/.exec(b)||/(webkit|opera)(?:.*version)?[ \/]([\w.]+)/.exec(b)||/(msie) ([\w.]+)/.exec(b)||[];k=b[1];b=parseFloat(b[2]);switch(k){case "msie":k="ie";
b=r.documentMode||b;break;case "firefox":k="ff";break;case "ipod":case "ipad":case "iphone":k="ios";break;case "webkit":k="safari"}l.browser={name:k,version:b};l.browser[k]=!0;for(var f=0,D=c.browsers.length;f<D;f++)for(var p in c.browsers[f])if(k===p){e(p);for(var A=c.browsers[f][p].max,m=c.browsers[f][p].min;m<=A;m++)b>m?(c.browserCss.gt&&e("gt-"+p+m),c.browserCss.gte&&e("gte-"+p+m)):b<m?(c.browserCss.lt&&e("lt-"+p+m),c.browserCss.lte&&e("lte-"+p+m)):b===m&&(c.browserCss.lte&&e("lte-"+p+m),c.browserCss.eq&&
e("eq-"+p+m),c.browserCss.gte&&e("gte-"+p+m))}else e("no-"+p);e(k);e(k+parseInt(b,10));"ie"===k&&9>b&&n("abbr article aside audio canvas details figcaption figure footer header hgroup main mark meter nav output progress section summary time video".split(" "),function(a){r.createElement(a)});n(x.pathname.split("/"),function(a,b){if(2<this.length&&this[b+1]!==z)b&&e(this.slice(b,b+1).join("-").toLowerCase()+c.section);else{a=a||"index";var f=a.indexOf(".");0<f&&(a=a.substring(0,f));u.id=a.toLowerCase()+
c.page;b||e("root"+c.section)}});l.screen={height:a.screen.height,width:a.screen.width};v();var C=0;a.addEventListener?a.addEventListener("resize",t,!1):a.attachEvent("onresize",t)})(window);
(function(a,z){function e(a){var e=a.charAt(0).toUpperCase()+a.substr(1),c;a:{a=(a+" "+t.join(e+" ")+e).split(" ");for(c in a)if(n[a[c]]!==z){c=!0;break a}c=!1}return!!c}var q=a.document.createElement("i"),n=q.style,v=" -o- -moz- -ms- -webkit- -khtml- ".split(" "),t=["Webkit","Moz","O","ms","Khtml"],r=a[a.head_conf&&a.head_conf.head||"head"],k={gradient:function(){n.cssText=("background-image:"+v.join("gradient(linear,left top,right bottom,from(#9f9),to(#fff));background-image:")+v.join("linear-gradient(left top,#eee,#fff);background-image:")).slice(0,
-17);return!!n.backgroundImage},rgba:function(){n.cssText="background-color:rgba(0,0,0,0.5)";return!!n.backgroundColor},opacity:function(){return""===q.style.opacity},textshadow:function(){return""===n.textShadow},multiplebgs:function(){n.cssText="background:url(//:),url(//:),red url(//:)";return/(url\s*\(.*?){3}/.test(n.background)},boxshadow:function(){return e("boxShadow")},borderimage:function(){return e("borderImage")},borderradius:function(){return e("borderRadius")},cssreflections:function(){return e("boxReflect")},
csstransforms:function(){return e("transform")},csstransitions:function(){return e("transition")},touch:function(){return"ontouchstart"in a},retina:function(){return 1<a.devicePixelRatio},fontface:function(){var a=r.browser.version;switch(r.browser.name){case "ie":return 9<=a;case "chrome":return 13<=a;case "ff":return 6<=a;case "ios":return 5<=a;case "android":return!1;case "webkit":return 5.1<=a;case "opera":return 10<=a;default:return!1}}},x;for(x in k)k[x]&&r.feature(x,k[x].call(),!0);r.feature()})(window);
(function(a,z){function e(){}function q(d,a){if(d){"object"===typeof d&&(d=[].slice.call(d));for(var y=0,b=d.length;y<b;y++)a.call(d,d[y],y)}}function n(d,a){var y=Object.prototype.toString.call(a).slice(8,-1);return a!==z&&null!==a&&y===d}function v(d){return n("Function",d)}function t(d){d=d||e;d._done||(d(),d._done=1)}function r(d){var a={};if("object"===typeof d)for(var g in d)d[g]&&(a={name:g,url:d[g]});else a=d.split("/"),a=a[a.length-1],g=a.indexOf("?"),a={name:-1!==g?a.substring(0,g):a,url:d};
return(d=m[a.name])&&d.url===a.url?d:m[a.name]=a}function k(a){a=a||m;for(var d in a)if(a.hasOwnProperty(d)&&4!==a[d].state)return!1;return!0}function x(a){a.state=2;q(a.onpreload,function(a){a.call()})}function u(a,b){a.state===z&&(a.state=1,a.onpreload=[],c({url:a.url,type:"cache"},function(){x(a)}))}function w(a,b){b=b||e;4===a.state?b():3===a.state?h.ready(a.name,b):1===a.state?a.onpreload.push(function(){w(a,b)}):(a.state=3,c(a,function(){a.state=4;b();q(A[a.name],function(a){t(a)});B&&k()&&
q(A.ALL,function(a){t(a)})}))}function c(d,b){b=b||e;var g;/\.css[^\.]*$/.test(d.url)?(g=f.createElement("link"),g.type="text/"+(d.type||"css"),g.rel="stylesheet",g.href=d.url):(g=f.createElement("script"),g.type="text/"+(d.type||"javascript"),g.src=d.url);g.onload=g.onreadystatechange=function(d){d=d||a.event;if("load"===d.type||/loaded|complete/.test(g.readyState)&&(!f.documentMode||9>f.documentMode))g.onload=g.onreadystatechange=g.onerror=null,b()};g.onerror=function(a){g.onload=g.onreadystatechange=
g.onerror=null;b()};g.async=!1;g.defer=!1;d=f.head||f.getElementsByTagName("head")[0];d.insertBefore(g,d.lastChild)}function b(){f.body?B||(B=!0,q(D,function(a){t(a)})):(a.clearTimeout(h.readyTimeout),h.readyTimeout=a.setTimeout(b,50))}function l(){f.addEventListener?(f.removeEventListener("DOMContentLoaded",l,!1),b()):"complete"===f.readyState&&(f.detachEvent("onreadystatechange",l),b())}var f=a.document,D=[],p=[],A={},m={},C="async"in f.createElement("script")||"MozAppearance"in f.documentElement.style||
a.opera,F,B,G=a.head_conf&&a.head_conf.head||"head",h=a[G]=a[G]||function(){h.ready.apply(null,arguments)};h.load=C?function(){var a=arguments,b=a[a.length-1],g={};v(b)||(b=null);q(a,function(d,c){d!==b&&(d=r(d),g[d.name]=d,w(d,b&&c===a.length-2?function(){k(g)&&t(b)}:null))});return h}:function(){var a=arguments,b=[].slice.call(a,1),c=b[0];if(!F)return p.push(function(){h.load.apply(null,a)}),h;c?(q(b,function(a){v(a)||u(r(a))}),w(r(a[0]),v(c)?c:function(){h.load.apply(null,b)})):w(r(a[0]));return h};
h.js=h.load;h.test=function(a,b,c,f){a="object"===typeof a?a:{test:a,success:b?n("Array",b)?b:[b]:!1,failure:c?n("Array",c)?c:[c]:!1,callback:f||e};(b=!!a.test)&&a.success?(a.success.push(a.callback),h.load.apply(null,a.success)):!b&&a.failure?(a.failure.push(a.callback),h.load.apply(null,a.failure)):f();return h};h.ready=function(a,b){if(a===f)return B?t(b):D.push(b),h;v(a)&&(b=a,a="ALL");if("string"!==typeof a||!v(b))return h;var c=m[a];if(c&&4===c.state||"ALL"===a&&k()&&B)return t(b),h;(c=A[a])?
c.push(b):A[a]=[b];return h};h.ready(f,function(){k()&&q(A.ALL,function(a){t(a)});h.feature&&h.feature("domloaded",!0)});if("complete"===f.readyState)b();else if(f.addEventListener)f.addEventListener("DOMContentLoaded",l,!1),a.addEventListener("load",b,!1);else{f.attachEvent("onreadystatechange",l);a.attachEvent("onload",b);var E=!1;try{E=null==a.frameElement&&f.documentElement}catch(d){}E&&E.doScroll&&function y(){if(!B){try{E.doScroll("left")}catch(g){a.clearTimeout(h.readyTimeout);h.readyTimeout=
a.setTimeout(y,50);return}b()}}()}setTimeout(function(){F=!0;q(p,function(a){a()})},300)})(window);